-- Deploy todoliste:create_tables to pg
-- Début de la transaction
BEGIN; 

-- Pour ne pas avoir d'erreurs on supprime les tables si elles existent déjà
DROP TABLE IF EXISTS "list", "importance", "user";

-- Création de la table "importance"
-- on l'a créé d'abord car elle n'a pas de dépendance
CREATE TABLE "importance" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "color" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Création de la table "user"
-- on créée la table "user" avant la table "list" car cette dernière est reliée à la table user via "user_id" INTEGER NOT NULL REFERENCES "user"("id")
CREATE TABLE "user" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Création de la table "list"
-- La table "list"  est liée aux 2 autres tables donc on l'a créée en dernier 
CREATE TABLE "list" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "importance_id" INTEGER REFERENCES "importance"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id")
);

-- Fin de la transaction
COMMIT;

